version: 1.2
workflows:
- name: main
  primaryDescriptorPath: /Galaxy-Workflow-VGP_assembly_decontamination_pipeline.ga
  subclass: Galaxy
  testParameterFiles:
  - /Galaxy-Workflow-VGP_assembly_decontamination_pipeline-tests.yml
